config/routes.rb
Rails.application.routes.draw do
  # get "users/edit"
  get "home/index"
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  scope "/checkout" do 
    get "shipping_information", to: "checkout#shipping_information", as: "checkout_shipping_information"
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
    post "update_shipping_information", to: "checkout#update_shipping_information", as: "update_shipping_information"  # Add this line

  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :products
  resources :customers
  resources :cart_items
  resources :carts, only: [:show]
  resources :orders

  root to: "home#index"










  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    belongs_to :user, optional: true
    before_save :set_subtotal

    def subtotal
        cart_items.collect {|cart_item| cart_item.valid? ? (cart_item.unit_price*cart_item.quantity) : 0}.sum
    end

    private

    def set_subtotal
        self[:subtotal] = subtotal
    end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :product

    before_save :set_unit_price
    before_save :set_total_price


    def unit_price
        if persisted?
            self[:unit_price]
        else
            product.price
        end
    end

    def total_price
        unit_price * quantity
    end

    private
    def set_unit_price
        self[:unit_price] = unit_price
    end

    def set_total_price
        self[:total_price] = quantity * set_unit_price
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :category_type, presence: true
    validates :category_type, uniqueness: true

    def self.ransackable_associations(auth_object = nil)
        ["product_categories", "products"]
    end

    def self.ransackable_attributes(auth_object = nil)
        ["category_description", "category_type", "created_at", "id", "id_value", "updated_at"]
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :province

    validates :street_address, :city, :postal_code, :email, presence: true
    validates :postal_code, format: { with: /\A[A-Za-z]\d[A-Za-z][ -]?\d[A-Za-z]\d\z/, message: "must be a valid postal code" }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :products, through: :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_many :cart_items
    has_many :order_items
    has_many :orders, through: :order_items

    validates :product_name, :brand, :price, :ingredients, presence: true
    validates :price, numericality: { greater_than_or_equal_to: 0.01 }

    def self.search(keywords, category_id)
        products = all

        if keywords.present?
            products = products.where("product_name LIKE ?", "%#{keywords}%")
        end

        if category_id.present?
            products = products.where(category_id: category_id)
        end

        products
    end 

    def self.ransackable_associations(auth_object = nil)
        ["category"]
    end

    def self.ransackable_attributes(auth_object = nil)
        ["brand", "category_id", "created_at", "id", "ingredients", "price", "product_name", "ranking", "updated_at"]
    end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "id", "id_value", "product_id", "updated_at"]
  end
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :users

    validates :province_name, presence: true, uniqueness: true
    validates :alpha_code, presence: true, length: { is: 2 }, uniqueness: true

    def self.ransackable_associations(auth_object = nil)
        ["users"]
    end

    def self.ransackable_attributes(auth_object = nil)
        ["alpha_code", "created_at", "id", "id_value", "province_name", "tax", "updated_at"]
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province, optional: true
  has_one :cart
  has_many :orders

  def self.ransackable_attributes(auth_object = nil)
    ["city", "created_at", "email", "encrypted_password", "id", "id_value", "postal_code", "province_id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "street_address", "updated_at"]
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :authenticate_user!

    def show
        @cart_items = current_order.cart_items
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_order
        # if !session[:cart_id].nil?
        #     Cart.find(session[:cart_id])
        # else
        #     Cart.new
        # end
        # if session[:cart_id].present?
        #     Cart.find(session[:cart_id]) # Find the cart by session ID

        #     if cart.user != current_user
        #         cart = Cart.create(user: current_user)
        #         session[:cart_id] = cart.id
        #     end
        #     cart
        # else
        #     cart = Cart.find_by(user: current_user) # Create a new cart and save it

        #     # Creates a new cart if no existing cart exists
        #     unless cart
        #         cart = Cart.create(user: current_user)
        #     end
            
        #     session[:cart_id] = cart.id # Store the new cart's ID in the session
        #     cart
        # end


        if current_user
            cart = current_user.cart || Cart.create(user_id: current_user.id)
        else
            cart = Cart.find_by(id: session[:cart_id], user_id: nil)
        end 

        # session[:cart_id] = cart.id if cart.persisted?

        if cart && cart.persisted?
            session[:cart_id] = cart.id
          end

        cart
    end


end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_cart_item.html.erb
<% if !@cart_item.nil? && @cart_item.errors.any? %>
    <ul>
        <% @cart_items.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<div class="columns is-multiline is-vcentered">
              <div class="column is-12 is-8-widescreen mb-8 mb-0-widescreen">
                <div class="is-hidden-touch columns is-multiline" style="border-bottom: 1px solid grey;">
                  <div class="column is-6">
                    <h4 class="has-text-grey has-text-weight-bold mb-6" style="font-size: 16px;" data-config-id="header1">Description</h4>
                  </div>
                  <div class="column is-2">
                    <h4 class="has-text-grey has-text-weight-bold mb-6" style="font-size: 16px;" data-config-id="header2">Price</h4>
                  </div>

                  <div class="column is-2">
                    <h4 class="has-text-grey has-text-weight-bold mb-6" style="font-size: 16px;" data-config-id="header4">Subtotal</h4>
                  </div>
                </div>
                <div class="mb-12 py-6">




<% if @cart_items.size>0 %>
    <% @cart_items.each do |item| %>
                  <div class="columns is-vcentered is-multiline">
                            <div class="column is-6-desktop is-7-tablet mb-6 mb-0-tablet">
                                <div class="columns is-vcentered is-multiline">
                                                <div class="column is-4-tablet mb-3">
                                                    <div class="is-flex has-background-light is-justify-content-center is-align-items-center" style="width: 96px; height: 128px;">
                                                        <img class="image is-fullwidth" style="object-fit: contain;" src="yofte-assets/images/basketball.png" alt="" data-config-id="image2">
                                                    </div>
                                                </div>

                                                <div class="column is-8">
                                                    <h3 class="subtitle mb-2 has-text-weight-bold" data-config-id="title2">
                                                        <%= link_to item.product.product_name, product_path(item.product_id) %>
                                                    </h3>
                                                </div>
                                </div>
                            </div>

                            <div class="column is-2 is-hidden-touch">
                                <p class="subtitle has-text-info mb-0 has-text-weight-bold" data-config-id="price2"><%= number_to_currency item.product.price %></p>
                            </div>



                            <div class="column is-2">
                            <p class="subtitle has-text-info has-text-weight-bold" data-config-id="price2">
                                <%= number_to_currency item.total_price %>
                            </p>
                            </div>
                  </div>
                  <div class="columns">
                    <div class="column">
                        <%= form_for(item) do |f| %>
                            <%= f.hidden_field :product_id, value: item.product.id %>

                            <div class="field has-addons">
                                <div class="select is-small">
                                    <%= f.select :quantity, (1..10).to_a, { selected: item.quantity.to_i }, { class: 'select is-small' } %>
                                </div>
                            <div class="control">
                                <button type="submit" class="button is-primary is-small">Update</button>
                            </div>
                            </div>
                        <% end %>
                    </div>
                    <div class="column is-danger">
                        <%= link_to 'Delete', item, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to remove this item from your cart?' }, class: 'button is-danger' %>
                    </div>
                  </div>




    <% end %>
<% else %>
<% end %>




                </div>
              </div>
              <div class="column is-12 is-4-widescreen">
                <div class="has-background-info p-6 p-16-desktop">
                  <h3 class="title is-size-3 has-text-white mb-6" data-config-id="summary-header">Cart totals</h3>
                  <div class="mb-8 pb-5 is-flex is-justify-content-space-between is-align-items-center" style="border-bottom: 1px solid rgba(255, 255, 255, 0.3);">
                    <span class="has-text-light" data-config-id="s-header1">Subtotal</span>
                    <span class="subtitle has-text-white has-text-weight-bold" data-config-id="s-value1">
                        <%= number_to_currency current_order.subtotal %>
                    </span>
                  </div>


                  <div class="mb-10 is-flex is-justify-content-space-between is-align-items-center">
                    <span class="title is-size-5 mb-0 has-text-white has-text-weight-bold" data-config-id="s-header5">Order total</span>
                    <span class="title is-size-5 mb-0 has-text-white has-text-weight-bold" data-config-id="s-value5">$100.67</span>
                  </div>
                  <%= link_to "Proceed to Shipping Information", checkout_shipping_information_path, class: "button is-primary" %>

                </div>
              </div>
</div>


app/views/carts/show.html.erb
<div class="cart_item">
    <%= render "carts/cart_item"%>
</div>

