config/routes.rb
Rails.application.routes.draw do
  # get "users/edit"
  get "home/index"
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  scope "/checkout" do 
    get "shipping_information", to: "checkout#shipping_information", as: "checkout_shipping_information"
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
    post "update_shipping_information", to: "checkout#update_shipping_information", as: "update_shipping_information"  # Add this line

  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :products
  resources :customers
  resources :cart_items
  resources :carts, only: [:show]
  resources :orders

  root to: "home#index"










  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_many :cart_items
    has_many :order_items
    has_many :orders, through: :order_items

    validates :product_name, :brand, :price, :ingredients, presence: true
    validates :price, numericality: { greater_than_or_equal_to: 0.01 }

    def self.search(keywords, category_id)
        products = all

        if keywords.present?
            products = products.where("product_name LIKE ?", "%#{keywords}%")
        end

        if category_id.present?
            products = products.where(category_id: category_id)
        end

        products
    end 

    def self.ransackable_associations(auth_object = nil)
        ["category"]
    end

    def self.ransackable_attributes(auth_object = nil)
        ["brand", "category_id", "created_at", "id", "ingredients", "price", "product_name", "ranking", "updated_at"]
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :set_product, only: %i[ show edit update destroy ]
  # GET /products or /products.json
  def index
    @categories = Category.all
    set_cart_item


    keywords = params[:keywords]
    category_id = params.dig(:category, :id)

    @products = Product.limit(50)

    if keywords.present?
      @products = @products.where("product_name LIKE ?", "%#{keywords}%")
    end

    if category_id.present?
      @products = @products.where(category_id: category_id)
    end
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
    set_cart_item


  end

  private
  def product_params
    params.require(:products).permit(:product_name, :price)
  end

  def set_cart_item
    if current_user
      @cart_item = current_order.cart_items.new
    else
      @cart_item = nil
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="column is-one-third">
        <div class="card">
            <div class="card-image">
                <figure class="image is-4by3">
                    <img
                        src="https://bulma.io/assets/images/placeholders/1280x960.png"
                        alt="Placeholder image"
                    />
                </figure>
            </div>

            <% if controller_name == "products" && action_name == "index" %>
                <div class="card-content">
                    <div class="media">
                        <div class="media-content">
                            <p class="title is-4">
                                <% if show_link %>
                                    <%= link_to product.product_name, product %> <!-- Link on the index page -->
                                <% else %>
                                    <%= product.product_name %> <!-- Plain text on the show page -->
                                <% end %>
                            </p>
                        </div>
                    </div>
                </div>
            <% end %>

            <footer class="card-footer">
                <p class="card-footer-item">
                    <%= number_to_currency product.price %>
                </p>

            </footer>
        </div>
</div>

app/views/products/index.html.erb
<%= form_tag products_path, :method => 'get' do %>
  <%= text_field_tag :keywords, params[:keywords], placeholder: "Search for product..." %>

  <%= collection_select :category, :id,  @categories, :id, :category_type, { include_blank: 'Select Category' } %>

  <%= submit_tag "Search"%>
<% end %>

<div class="columns is-multiline">
    <% @products.each do |product| %>
      <%= render partial: 'product', locals: { product: product, show_link: true } %>
    <% end %>
</div>

app/views/products/show.html.erb
<div class="columns">
    <%= render partial: 'product', locals: { product: @product, show_link: false } %>
    <div class="column is-two-thirds">
        <span class="has-text-grey-dark">
            <%= @product.brand %>
        </span>

        <h1 class="title is-2 has-text-black"><%= @product.product_name %></h1>

        <p class="has-text-grey">Category: <%= link_to @product.category.category_type, category_path(@product.category) %></p>

        <p class="has-text-grey">Ranking: <%= @product.ranking %> / 5</p>

        <article class="message">
            <div class="message-header">
                <p>Ingredients</p>
                <button class="delete" aria-label="delete"></button>
            </div>
            <div class="message-body">
                <%= @product.ingredients %>
            </div>
        </article>

        <% if current_user %>
            <%= form_for(@cart_item, remote: true) do |f| %>
                <%= f.hidden_field :product_id, value: @product.id %>

                <div class="field has-addons">
                    <div class="select is-small">
                    <%= f.select :quantity, (1..10).to_a, { selected: @cart_item.quantity.to_i }, { class: 'select is-small' } %>
                    </div>
                    <div class="control">
                    <%= f.submit "Add", class: 'button is-primary is-small' %>
                    </div>
                </div>
            <% end %>
        <% else %>
          <%= link_to 'Log in to add to cart', new_user_session_path, class: "button is-primary is-small" %>
        <% end %>

    </div> 
</div>