config/routes.rb
Rails.application.routes.draw do
  # get "users/edit"
  get "home/index"
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  scope "/checkout" do 
    get "shipping_information", to: "checkout#shipping_information", as: "checkout_shipping_information"
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
    post "update_shipping_information", to: "checkout#update_shipping_information", as: "update_shipping_information"  # Add this line

  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :products
  resources :customers
  resources :cart_items
  resources :carts, only: [:show]
  resources :orders

  root to: "home#index"










  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    belongs_to :user, optional: true
    before_save :set_subtotal

    def subtotal
        cart_items.collect {|cart_item| cart_item.valid? ? (cart_item.unit_price*cart_item.quantity) : 0}.sum
    end

    private

    def set_subtotal
        self[:subtotal] = subtotal
    end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :product

    before_save :set_unit_price
    before_save :set_total_price


    def unit_price
        if persisted?
            self[:unit_price]
        else
            product.price
        end
    end

    def total_price
        unit_price * quantity
    end

    private
    def set_unit_price
        self[:unit_price] = unit_price
    end

    def set_total_price
        self[:total_price] = quantity * set_unit_price
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products

    validates :category_type, presence: true
    validates :category_type, uniqueness: true

    def self.ransackable_associations(auth_object = nil)
        ["product_categories", "products"]
    end

    def self.ransackable_attributes(auth_object = nil)
        ["category_description", "category_type", "created_at", "id", "id_value", "updated_at"]
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :province

    validates :street_address, :city, :postal_code, :email, presence: true
    validates :postal_code, format: { with: /\A[A-Za-z]\d[A-Za-z][ -]?\d[A-Za-z]\d\z/, message: "must be a valid postal code" }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :products, through: :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_many :cart_items
    has_many :order_items
    has_many :orders, through: :order_items

    validates :product_name, :brand, :price, :ingredients, presence: true
    validates :price, numericality: { greater_than_or_equal_to: 0.01 }

    def self.search(keywords, category_id)
        products = all

        if keywords.present?
            products = products.where("product_name LIKE ?", "%#{keywords}%")
        end

        if category_id.present?
            products = products.where(category_id: category_id)
        end

        products
    end 

    def self.ransackable_associations(auth_object = nil)
        ["category"]
    end

    def self.ransackable_attributes(auth_object = nil)
        ["brand", "category_id", "created_at", "id", "ingredients", "price", "product_name", "ranking", "updated_at"]
    end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "id", "id_value", "product_id", "updated_at"]
  end
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :users

    validates :province_name, presence: true, uniqueness: true
    validates :alpha_code, presence: true, length: { is: 2 }, uniqueness: true

    def self.ransackable_associations(auth_object = nil)
        ["users"]
    end

    def self.ransackable_attributes(auth_object = nil)
        ["alpha_code", "created_at", "id", "id_value", "province_name", "tax", "updated_at"]
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province, optional: true
  has_one :cart
  has_many :orders

  def self.ransackable_attributes(auth_object = nil)
    ["city", "created_at", "email", "encrypted_password", "id", "id_value", "postal_code", "province_id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "street_address", "updated_at"]
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cart.html.erb
<%= link_to "#{current_order.cart_items.size} items in cart & price #{current_order.subtotal}", cart_path(current_order)  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "E Commerce Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css"
    >
    <link href="https://cdn.lineicons.com/5.0/lineicons.css" rel="stylesheet" />


  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do %>
            <h1 class="title">SkinNest</h1>
          <% end %>
      </div>

      <div class="navbar-menu">
          <div class="navbar-start">
            <%= link_to "Shop", products_url, class: "navbar-item" %>

            <%= link_to "Categories", categories_path, class: "navbar-item" %>

            <%= link_to "Orders", orders_path, class: "navbar-item" %>

          </div>

          <div class="navbar-end">
          <% if current_order && current_order.id.present? %>
            <%= link_to cart_path(current_order), class: "navbar-item" do %>
              <i class="lni lni-cart-1 has-text-light" style="font-size: 30px;"></i>
            <% end %>
          <% else %>
              <%= link_to new_user_session_path, class: "navbar-item" do %>
                <i class="lni lni-cart-1 has-text-light" style="font-size: 30px;"></i>
              <% end %>
          <% end %>
          </div>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div>
      <% if user_signed_in? %>
        <%= link_to "Profile", edit_user_registration_path %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete%>
      <% else %>
        <%= link_to "Login", new_user_session_path %>
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>

    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
  </body>
</html>